/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blogspot_rock88dev_nativegldemo_GLNativeProxy */

#ifndef _Included_com_blogspot_rock88dev_nativegldemo_GLNativeProxy
#define _Included_com_blogspot_rock88dev_nativegldemo_GLNativeProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blogspot_rock88dev_nativegldemo_GLNativeProxy
 * Method:    GL_Native_Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_blogspot_rock88dev_nativegldemo_GLNativeProxy_GL_1Native_1Init
  (JNIEnv *, jclass);

/*
 * Class:     com_blogspot_rock88dev_nativegldemo_GLNativeProxy
 * Method:    GL_Native_Deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_blogspot_rock88dev_nativegldemo_GLNativeProxy_GL_1Native_1Deinit
  (JNIEnv *, jclass);

/*
 * Class:     com_blogspot_rock88dev_nativegldemo_GLNativeProxy
 * Method:    GL_Native_SurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_blogspot_rock88dev_nativegldemo_GLNativeProxy_GL_1Native_1SurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_blogspot_rock88dev_nativegldemo_GLNativeProxy
 * Method:    GL_Native_Draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_blogspot_rock88dev_nativegldemo_GLNativeProxy_GL_1Native_1Draw
  (JNIEnv *, jclass);

/*
 * Class:     com_blogspot_rock88dev_nativegldemo_GLNativeProxy
 * Method:    GL_Native_GetFPS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_blogspot_rock88dev_nativegldemo_GLNativeProxy_GL_1Native_1GetFPS
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
